apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    :80 {
        # Redirect all traffic to Vikunja service
        reverse_proxy vikunja:3456

        # Optional: specific route for Adminer
        handle_path /admin* {
            reverse_proxy adminer:8080
        }

        log {
            output stdout
            format json
        }
    }
