apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
        - name: vikunja
          image: vikunja/vikunja:latest
          ports:
            - containerPort: 3456 
          env:
            - name: VIKUNJA_DATABASE_TYPE
              value: "postgres"
            - name: VIKUNJA_DATABASE_HOST
              value: "vikunja-database"
            - name: VIKUNJA_DATABASE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: vikunja-secrets
                  key: POSTGRES_DB
            - name: VIKUNJA_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: vikunja-secrets
                  key: POSTGRES_USER
            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-secrets
                  key: VIKUNJA_DATABASE_PASSWORD
            - name: VIKUNJA_SERVICE_JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: vikunja-secrets
                  key: VIKUNJA_SERVICE_JWTSECRET
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: "http://localhost/"
            - name: VIKUNJA_SERVICE_FRONTENDURL
              value: "http://localhost/"
            - name: VIKUNJA_CORS_ENABLE
              value: "false"
          volumeMounts:
            - name: files
              mountPath: /app/vikunja/files
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: vikunja-files-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vikunja
spec:
  ports:
    - port: 3456
      targetPort: 3456
  selector:
    app: vikunja
