apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja-v1
  labels:
    app: vikunja
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vikunja
      version: v1
  template:
    metadata:
      labels:
        app: vikunja
        version: v1
    spec:
      containers:
        - name: vikunja
          image: vikunja/vikunja:1.0.0-rc3
          ports:
            - containerPort: 3456 
          env:
            - name: VIKUNJA_DATABASE_TYPE
              value: "postgres"
            - name: VIKUNJA_DATABASE_HOST
              value: "vikunja-database"
            - name: VIKUNJA_DATABASE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: vikunja-secrets
                  key: POSTGRES_DB
            - name: VIKUNJA_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: vikunja-secrets
                  key: POSTGRES_USER
            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-secrets
                  key: POSTGRES_PASSWORD
            - name: VIKUNJA_SERVICE_JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: vikunja-secrets
                  key: JWT_SECRET
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: "http://localhost/"
            - name: VIKUNJA_SERVICE_FRONTENDURL
              value: "http://localhost/"
            - name: VIKUNJA_CORS_ENABLE
              value: "false"
          volumeMounts:
            - name: files
              mountPath: /app/vikunja/files
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: vikunja-files-pvc
